stocks:
  - NIFTY24FEBFUT
  - BANKNIFTY24FEBFUT

stages:

  stage1:
    - key: rsi
      operator: "<"
      value: 70

  stage2:
    - key: ema_9
      operator: ">"
      value: 0

  stage3:
    - key: adx
      operator: ">"
      value: 20