zerodha:
  api_key: "ttu1u7gc87m4g52f"
  api_secret: "zo3h4eyxzg8axlbettiaqamf1kpv1gy7"
  access_token: "" 

settings:
  #exchange: "MCX"
  exchange: "NSE"
  interval: "15minute"
  from_date: "2024-01-01"
  to_date: "2025-09-05"

