"""add watchlist and strategy config tables

Revision ID: 22312ddc73ce
Revises: b470e9bbda1b
Create Date: 2026-07-28 11:36:49.919900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22312ddc73ce'
down_revision: Union[str, Sequence[str], None] = 'b470e9bbda1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stoploss_pct', sa.Float(), nullable=False),
    sa.Column('target_pct', sa.Float(), nullable=False),
    sa.Column('trailing_pct', sa.Float(), nullable=False),
    sa.Column('max_cycles_per_day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_symbols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_symbols')
    op.drop_table('strategy_config')
    # ### end Alembic commands ###
