"""replace strategy_config with deployments

Revision ID: 9f5429c44037
Revises: 22312ddc73ce
Create Date: 2026-07-28 12:40:15.863273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5429c44037'
down_revision: Union[str, Sequence[str], None] = '22312ddc73ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('symbols_json', sa.Text(), nullable=False),
    sa.Column('capital', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stoploss_pct', sa.Float(), nullable=False),
    sa.Column('target_pct', sa.Float(), nullable=False),
    sa.Column('trailing_pct', sa.Float(), nullable=False),
    sa.Column('max_cycles_per_day', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('strategy_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('stoploss_pct', sa.FLOAT(), nullable=False),
    sa.Column('target_pct', sa.FLOAT(), nullable=False),
    sa.Column('trailing_pct', sa.FLOAT(), nullable=False),
    sa.Column('max_cycles_per_day', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('deployments')
    # ### end Alembic commands ###
